#Obter todos os professores
###
GET http://localhost:8080/api/v1/professor/list
Content-Type: application/json


#Criar um professor Maria
###
POST http://localhost:8080/api/v1/professor/new
Content-Type: application/json

{
  "nome": "Maria",
  "email": "maria@email.com"
}


###
#Obter o professor com id 1 (Maria)
GET http://localhost:8080/api/v1/professor/1


#Obter as unidades curriculares do professor com id 1 (Maria)
###
GET http://localhost:8080/api/v1/professor/1/unidades-curriculares/list


#Criar uma unidade curricular Matemática
###
POST http://localhost:8080/api/v1/unidade_curricular/new
Content-Type: application/json

{
  "nome": "Matemática 2",
  "codigo": "MAT2",
  "descricao": "Matemática 2",
  "ano": 1,
  "semestre": 1
}


###
#Adicionar a unidade curricular com id 1 (Matemática) ao professor com id 1 (Maria)
POST http://localhost:8080/api/v1/professor/1/unidades-curriculares/add/1


###
#Obter todas as unidades curriculares
GET http://localhost:8080/api/v1/unidade_curricular/list



